### ISSUE TITLE
LustyJuggler: "VIM is not a module"

### ISSUE THREAD

**Issue by ches** [alexgenco/neovim-ruby#12]
Hi,

Congrats on getting the plugin host this far and the `if_ruby` support merged!

The essentials seem to be working for me, e.g. a few things like `:ruby puts 'Hello!'`, `:ruby puts VIM::Buffer.count` are fine, but one of my only Ruby plugins is not: [LustyJuggler]. The plugin does a healthy dose of monkeypatching the `VIM` module, so that might be pertinent…

Whenever I invoke `:LustyJuggler`, I get:

```
Error detected while processing function provider#ruby#Call:
line   17:
VIM is not a module
Error detected while processing function lustyjuggler#LustyJugglerStart[1]..provider#ruby#Call:
line   17:
uninitialized constant LustyJ
```

If it helps to narrow getting to root of it, I don't use LustyExplorer at all—I don't hit its autoload and an `NVIM_RUBY` debug log confirms that (I can pastebin that if it's helpful).

I think it's clear the plugin host setup is generally working and there just may be something about this plugin raising an issue (hopefully obvious that it works fine for me in regular Vim), but in case it's helpful, here are some environment details:

##### Relevant bit from `:CheckHealth`

```
Checking: Ruby
  Ruby Version: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin14]
  Host Executable: /Users/ches/.gem/ruby/2.3.0/bin/neovim-ruby-host
  Host Version: 0.2.1
```

##### Neovim

Built from master via Homebrew about half an hour ago:

```
$ nvim --version
NVIM v0.1.5-612-g335be42
Build type: Dev
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20160713-6533-1yupakl/build/config -I/tmp/neovim-20160713-6533-1yupakl/src -I/tmp/neovim-20160713-6533-1yupakl/deps-build/usr/include -I/tmp/neovim-20160713-6533-1yupakl/deps-build/usr/include -I/tmp/neovim-20160713-6533-1yupakl/deps-build/usr/include -I/tmp/neovim-20160713-6533-1yupakl/deps-build/usr/include -I/tmp/neovim-20160713-6533-1yupakl/deps-build/usr/include -I/tmp/neovim-20160713-6533-1yupakl/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20160713-6533-1yupakl/build/src/nvim/auto -I/tmp/neovim-20160713-6533-1yupakl/build/include
Compiled by ches@Fio.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"
```

Let me know if there's more info I can provide.

[LustyJuggler]: https://github.com/sjbach/lusty

**Comment by alexgenco** [comment]
Thanks for writing this up. It looks this gem exposes 2 incompatibilities:

1. `nvim` exposes the `VIM` constant as a class, while `vim` exposes it as a module.
2. The `VIM::set_option` method takes 2 argument in `nvim` and 1 in `vim`.

I'm working on a fix for both of these, I'll try to get a patch release out later today if I can.

**Comment by ches** [comment]
> 1. `nvim` exposes the `VIM` constant as a class, while `vim` exposes it as a module.

Ah! This should seem obvious now from the error, but I was trusting the old documentation and hadn't seen it in the source yet.

Thanks!

**Comment by alexgenco** [comment]
@ches can you try `rake install`ing `neovim-ruby` from master and trying again?

**Comment by ches** [comment]
That's fixed it!

**Comment by alexgenco** [comment]
Just pushed v0.2.2, this should be good to go. Thanks!
