### ISSUE TITLE
Column position from Neovim::Window#cursor start at 0

### ISSUE THREAD

**Issue by cedlemo** [alexgenco/neovim-ruby#13]
In this little plugin : 

```ruby
Neovim.plugin do |plug|
   plug.command(:CursorPos, :nargs => 0) do |nvim|
      l, c = nvim.current.window.cursor
     nvim.command("echo 'l > #{l} c > #{c}'")
   end
end
```

When I run it , the column position is like an ruby array index, for example the starting position in the file : 

```ruby
[1, 0] # In vim I expected [1, 1]
```

I don't know if it is an issue or not.

**Comment by alexgenco** [comment]
Yeah this is a little weird, but as far as I can tell it matches the legacy behavior. If you run `:ruby p VIM::Window.current.cursor` in regular `vim`, you'll get the same result. Is it causing issues for you elsewhere?

**Comment by cedlemo** [comment]
No, I am just surprised because in vim/neovim the first column start to 1 (`echo col(".")` when you cursor is on the first column). I planned to write an `omnifunc` in ruby . This function is run twice and the first time it must return a position. So I guess that I will have to increment each position that has been computed in ruby and that I have to return to neovim/vim.

**Comment by alexgenco** [comment]
The mismatch between `col(".")` and `window.cursor` is definitely weird. One possibility would be to make the `#cursor` method return 1-indexed for both rows and columns in remote plugins, and keep the legacy behavior just for `:ruby` scripts. Although that kind of feels like replacing one confusing thing with another. If you feel OK about that workaround, I think I'll leave the behavior as it is for now and we can revisit if it comes up again.

**Comment by cedlemo** [comment]
> If you feel OK about that workaround, I think I'll leave the behavior as it is for now and we can revisit if it comes up again.

No problem, I understand.
Thanks.
