### ISSUE TITLE
Shada not disabled in all tests

### ISSUE THREAD

**Issue by jpleau** [alexgenco/neovim-ruby#16]
Hi.

I noticed that in neovim_spec.rb, nvim is ran with -i NONE, to disable shada.

However, in other tests, -i NONE is not passed, thus enabling ShaDa and altering the user's local shada file.

Is there a reason why it's not disabled? My first guess was that it was just forgotten. I can send a PR if -i NONE should be added to all instances of neovim that are launched.

Thanks !

**Comment by alexgenco** [comment]
Oh, honestly I think the `-i NONE` is a typo, intended to be `-u NONE`. I wasn't even really aware of the `-i` option. Good catch, feel free to open a PR as I probably wouldn't be able to get around to it for a little while.
