### ISSUE TITLE
$curbuf falls behind VIM::Buffer.current

### ISSUE THREAD

**Issue by ohjames** [alexgenco/neovim-ruby#18]
In vim $curbuf and VIM::Buffer.current are always the same, in neovim-ruby when I open and focus a new buffer then $curbuf does not update.

Some vim scripts can be replaced by a global replace of $curbuf with VIM::Buffer.current (such as oniwabandana).

**Comment by alexgenco** [comment]
What steps can reproduce this? Both `:new` and `:tabnew` are incrementing `$curbuf.number` for me.

**Comment by ohjames** [comment]
Try splitting the window and moving between them... this issue breaks the popular `ctrl-p`, `command-t` and `oniwabandana` extensions due to the behaviour I described. You can fix each of these extensions with a global replace of `$curbuf`.

**Comment by alexgenco** [comment]
This should be somewhat resolved by https://github.com/alexgenco/neovim-ruby/commit/1c2e41c56e8984d04edeb8fc61884593c1f925a5. Although command-t is still broken when run from a tab, which I believe is a [neovim issue](https://github.com/neovim/neovim/issues/5332#issuecomment-248514091).

**Comment by alexgenco** [comment]
This should be resolved now. Lemme know if you have more issues.
