### ISSUE TITLE
setting the line position of VIM::Window.current.cursor to 0 does not work.

### ISSUE THREAD

**Issue by ohjames** [alexgenco/neovim-ruby#19]
e.g.

```
VIM::Window.current.cursor = [ 0, 5 ]
```

The first argument of `0` means "don't change the line position" but neovim-ruby reports "Index out of bounds".

**Comment by alexgenco** [comment]
Is that the behavior in vim? Should be easy enough to fix. I'm out of town for a few days, so feel free to open a pull request. Otherwise I'll get to it sometime next week.

**Comment by alexgenco** [comment]
@ohjames just merged a fix to match the behavior of `vim`, which is actually slightly different than you described. It looks like giving a line <= 0 actually moves the the cursor to the first line (and same for the column).

You can give it a try by `rake install`ing on master if you'd like.

**Comment by ohjames** [comment]
@alexgenco nope: see `:help cursor`. I quote:

> If {lnum} is zero, the cursor will stay in the current line.

This extension I'm using relies on that fact.

**Comment by ohjames** [comment]
Note also:

> Positions the cursor at the column (byte count) {col} in the line {lnum}.  The *first column is one*.

**Comment by alexgenco** [comment]
@ohjames that isn't the behavior of the legacy vim `VIM::Window#cursor=` method though. Your example (`VIM::Window.current.cursor = [ 0, 5 ]`) moves the cursor to the first line, 5th column (0-indexed). It's not consistent with the `cursor()` function, and it isn't meant to be.

What exactly is the problem you're facing?

**Comment by ohjames** [comment]
> that isn't the behavior of the legacy vim VIM::Window#cursor= method though.

Just test it, you'll see you're incorrect.

**Comment by ohjames** [comment]
Ah, you're correct.
