### ISSUE TITLE
Autocmd

### ISSUE THREAD

**Issue by MatLeb** [alexgenco/neovim-ruby#24]
I have a problem with autocmds :

- Case 1

1.  I start nvim
2. run a command from a test plugging (ex SetLine)
3. trigger an event (ex: BufEnter)
=> it works

- Case 2

1. I start nvim
2. no command call
3. trigger an event 
=> autocmd has not effect

**Comment by alexgenco** [comment]
Thanks for the report. I'm assuming the autocmd is defined in the same plugin as the command in case 1, number 2?

**Comment by justinmk** [comment]
If possible please try again on neovim master.

**Comment by alexgenco** [comment]
Works for me! Thanks all.
