### ISSUE TITLE
host dies on `:ruby` syntax error 

### ISSUE THREAD

**Issue by justinmk** [alexgenco/neovim-ruby#29]
Using nvim 0.2.x and neovim-ruby 0.3.1, try this:

    :ruby puts(

That kills the host:

```
Error detected while processing function provider#ruby#Call:                                                     
line   17:                                                                                                       
Channel was closed by the client
```

**Comment by alexgenco** [comment]
Looks like I needed to add some special handling of `SyntaxError`. Fix on master https://github.com/alexgenco/neovim-ruby/commit/2a0194d09a7114a2819c3ae01c1babef34e28a8b
