### ISSUE TITLE
Does this need to be installed for each ruby version?

### ISSUE THREAD

**Issue by dewyze** [alexgenco/neovim-ruby#37]
I use rvm and have a variety of ruby versions on my machine. Not all projects share the same ruby-version, do I need to install this for each ruby-version on my machine?

When I run `:CheckHealth` I get

```
## Ruby provider (optional)
  - INFO: Ruby: ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
  - WARNING: Missing "neovim" gem.
    - SUGGESTIONS:
      - Run in shell: gem install neovim
      - Is the gem bin directory in $PATH? Check `gem environment`.
      - If you are using rvm/rbenv/chruby, try "rehashing".
```

If I change projects, that version changes. I just want confirm that it does need to be installed for each ruby version and there is no way for it to be installed only once.

**Comment by alexgenco** [comment]
@dewyze are you using rvm gemsets? If you install the neovim gem for a particular Ruby version, do you get a clean `:CheckHealth` when launching `nvim` from that ruby version?

**Comment by dewyze** [comment]
I am using gemsets, if I install it globally on a version it works. It is just unfortunate to need to install it every time I install a new ruby version.

**Comment by alexgenco** [comment]
Yeah unfortunately I think that's expected at this point. I'm thinking a possible improvement would be if we added the ability to set an env var like `NVIM_RUBY_HOST_COMMAND="rvm system do neovim-ruby-host"` to pin it to the system gem version. @justinmk thoughts? Happy to put together a PR.

**Comment by alexgenco** [comment]
Correction, looks like `g:ruby_host_prog` would match better with python: https://github.com/neovim/neovim/blob/master/runtime/autoload/provider/pythonx.vim#L51

**Comment by alexgenco** [comment]
https://github.com/neovim/neovim/pull/6841 has been merged, so you should be able to use `let g:ruby_host_prog = 'rvm system do neovim-ruby-host'` after upgrading to nvim [nightly](https://github.com/neovim/neovim/releases/tag/nightly) and installing the `neovim` gem to the system gemset.

I'm gonna close this, but let me know if you have further issues.
