### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by jpleau** [alexgenco/neovim-ruby#39]
Hi!

Would it be possible to release a new minor version of neovim-ruby? The current 4.0.0 release is listed for neovim-0.1.7, while current HEAD is for 0.2.0. I'm working on getting the ruby-neovim package up to date for Debian/Ubuntu, and this would really help.

Thanks!

**Comment by alexgenco** [comment]
Happy to cut a new release, but just for my understanding... what do you mean "The current 4.0.0 release is listed for neovim-0.1.7"? Do you mean 0.4.0? Could the new package just include 0.4.0 without a gem release? (Again, a gem release is on my TODO list so I will probably do it regardless)

**Comment by jpleau** [comment]
Hi.

Sorry, 4.0.0 was a typo, I meant 0.4.0.

I was looking at this when I meant "the current release is listed for neovim-0.1.7":

https://github.com/alexgenco/neovim-ruby/blob/v0.4.0/lib/neovim/client.rb#L9

The documentation was generated using neovim-0.1.7, while current git HEAD's documentation was generated for 0.2.0.

I will probably have to wait for a gem release since Debian ruby package scripts use rubygems to look for new versions (it all works automagically).

Thanks !

**Comment by alexgenco** [comment]
Fair enough, will publish shortly.

**Comment by alexgenco** [comment]
Done, let me know if you need anything else https://rubygems.org/gems/neovim/versions/0.5.0
