### ISSUE TITLE
vader.vim missing from release build

### ISSUE THREAD

**Issue by jpleau** [alexgenco/neovim-ruby#40]
Hi

The directory spec/integration/runtime/vader.vim/ is empty in release tarballs. It looks like it's a git submodule, but is not fully included in the release. This makes it impossible to run the tests without cloning from git!

Would it be possible to include the submodule in release tarballs?

Thanks !

**Comment by alexgenco** [comment]
I don't know much about releases, but I looked into it a little bit and it doesn't look like there's a way to include submodules in Github releases. I don't personally see this as a problem; if you need to run the tests you should be using a cloned repo, as the [README suggests](https://github.com/alexgenco/neovim-ruby#contributing). I think the tarballs should be used for installation only.

Is there a use case here I'm missing?

**Comment by jpleau** [comment]
Hi.

I'll describe my use case: I am currently working on upgrading the Debian/Ubuntu package for neovim-ruby to the latest release. We have scripts that update ruby packages' source code using rubygems. (Not using git repos)

During package building (.deb), tests are ran. Now since vader.vim isn't included in the release, the tests that require it obviously fail, and package creation aborts.

I can work around it by either packaging vader.vim for Debian or disabling the tests that require it.

Hope that makes it a little bit more clear !

Thanks !

**Comment by alexgenco** [comment]
I just converted vader.vim from a submodule to a subtree. I'll try to release 0.5.1 tomorrow sometime, and it should include the vader.vim files.

**Comment by alexgenco** [comment]
I just released [0.5.1](https://rubygems.org/gems/neovim/versions/0.5.1). Can you check if this works for you?

**Comment by jpleau** [comment]
Hi.

Thanks, that fixed the testing issue I had !

**Comment by alexgenco** [comment]
@jpleau I made some updates that could potentially make this an issue again. I'm using vim-themis instead of vader now, and I'm installing it using `vim-flavor`, instead of checking it into the repo. Can you check if things are working with this change?

**Comment by jpleau** [comment]
Hi, not at home today so I can't test, but I can already tell it probably will break things on my end.

Network is completely disabled on build servers, so the plugin will probably fail to be downloaded and installed.

I can simply disable tests in the packaging (not the best option, but I understand it makes things easier on your side). Maybe I can patch the rakefile at build time to only run the functionnal tests, and disable the acceptance spec.

**Comment by alexgenco** [comment]
Running just the functional tests seems like a good option. Do you not have any control over how it runs tests? If so, you don't have to patch the Rakefile and can just run `rake spec:functional` instead of `rake`. Themis is a significantly larger codebase than Vader (and significantly larger than neovim-ruby itself), so I'd really rather it be included lazily.

**Comment by jpleau** [comment]
I believe I do have control yes, not sure why I proposed to patch the Rakefile at build time instead.

I'll try to work on it this week, will report back.

Thanks for letting me know of these changes, it's appreciated !

**Comment by alexgenco** [comment]
Feel free to reopen if you have issues.

**Comment by jpleau** [comment]
Quick test: it seemed to work fine on my side. I'll wait for an official release before going further. Thanks

**Comment by alexgenco** [comment]
@jpleau 0.7.1 was just released, FYI

**Comment by jpleau** [comment]
Awesome thanks. I actually upgraded my packaging yesterday to match current git master, will update everything this week!
