### ISSUE TITLE
lib/neovim/ruby_provider.rb is broken on release 0.7.0

### ISSUE THREAD

**Issue by anjos** [alexgenco/neovim-ruby#51]
If I use this release, neovim keeps complaining about StringIO not being defined with:

```text
NameError: uninitialized constant Neovim::RubyProvider::StringIO
```

Simple test - install the plugin, run `:UpdateRemotePlugins`, then run `:ruby puts 'hello'`.

Fixing: just `require "stringio"` on the header of `lib/neovim/ruby_provider.rb`. I hope it helps

**Comment by alexgenco** [comment]
Good catch! I thought that was stdlib but I guess not. Feel free to PR the change, otherwise I'll get to it probably next week.

**Comment by alexgenco** [comment]
Just pushed 0.7.1 to rubygems. Please reopen if you have further issues.
