### ISSUE TITLE
Finding ruby host using a system call doesn't work

### ISSUE THREAD

**Issue by cbcoutinho** [alexgenco/neovim-ruby#52]
Hi there,

I just came across a small problem I'm having with various ruby versions and neovim. I need to access different operating systems that for various reasons can't install `rvm` - I need to use the system ruby version. I have installed the neovim ruby package in my home directory (`~/.gem/ruby/2.x.y/bin/neovim-ruby-host`), and can find it using `which neovim-ruby-host`

instead of hard coding the location of the host, I was wondering if I could shell out the the system to find it _a la_ `let g:ruby_host_prog=system("which neovim-ruby-host")`. Unfortunately this doesn't quite work, and I'm left with the following timeout error when running `nvim +CheckHealth`:

```
## Ruby provider (optional)
  - INFO: Ruby: ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux-gnu]
  - INFO: Host: /home/chris/.gem/ruby/2.5.0/bin/neovim-ruby-host
  - ERROR: Command timed out: /home/chris/.gem/ruby/2.5.0/bin/neovim-ruby-host
    --version
  - OK: Latest "neovim" gem is installed:
```

It's kind of an error, and then also not. it says that the `neovim` gem is installed, but when I try to create a sample gem and `:UpdateRemotePlugins`, `neovim` doesn't` register them.

For what it's worth, the neovim-node-host package does work this way, specifically I have in my `init.vim`:

```
let g:npm_host_prog=system("which npm | sed 's/npm/neovim-node-host/'")
```

**Comment by alexgenco** [comment]
I just tried this locally and it failed when I did `system("which neovim-ruby-host")`, which contains a trailing newline, and worked when i did `systemlist("which neovim-ruby-host")[0]`, which strips the newline. Can you try the latter?

**Comment by cbcoutinho** [comment]
Thanks for getting back to me so quickly. This work around gets the job done!
