### ISSUE TITLE
Plugin is not being recognized

### ISSUE THREAD

**Issue by kitlangton** [alexgenco/neovim-ruby#7]
I've added the example plugin to `$VIMRUNTIME/rplugin/ruby/my_plugin.rb` and ran `:UpdateRemotePlugins`, but the plugin does not get registered and its commands do not become available. :(

Are there extra steps one must take in order to register the ruby host? Placing any empty `blah.py` at `$VIMRUNTIME/rplugin/python3/blah.py` seems to register just fine for some reason.

Thank you for your time! :dancers:

**Comment by alexgenco** [comment]
Hi @kitlangton, sorry about the confusion. Unfortunately the vim remote plugin functionality requires a change neovim-side, which I'm hoping to open a PR for later this week: https://github.com/neovim/neovim/compare/master...alexgenco:ruby_rplugin.

The README is misleading for sure, that was an oversight on my part. I'll make it more clear.

**Comment by kitlangton** [comment]
Thanks for the response! That's really exciting! Hopefully the ability to write Vim plugins in Ruby will tempt more Ruby people over to NeoVim. Thanks for your efforts :-D

**Comment by alexgenco** [comment]
Here's the PR: https://github.com/neovim/neovim/pull/4410

**Comment by tpbowden** [comment]
Is there a workaround for this without recompiling NeoVIm from a patched branch?

**Comment by alexgenco** [comment]
@tpbowden I think that might be the best option at this point, unfortunately. Although I don't think you need to recompile, just `make install` to copy the runtime files (could be wrong about that).

**Comment by tpbowden** [comment]
Yeah the make install is not necessary, all the .vim scripts in the runtime directory are executed from there

**Comment by alexgenco** [comment]
Ah, missed your edit. Yeah that works too.

**Comment by alexgenco** [comment]
PR is merged, I'm gonna close this.
